/// Flutter icons MyCustomImages
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomImages
///      fonts:
///       - asset: fonts/MyCustomImages.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyCustomImages {
  MyCustomImages._();

  static const _kFontFam = 'MyCustomImages';
  static const String? _kFontPkg = null;

  static const IconData delete = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg,);
}
